name: appwrite_flutter_accounts
description: A new Flutter package project.
version: 0.0.1
author: Damodar Lohani
homepage: https://github.com/lohanidamodar/appwrite_flutter_accounts

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^0.5.0-dev.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null






























