name: flappwrite_account_kit
description: A wrapper for Appwrite's Accounts service, makes it easy to use
  Accounts service, manage authentication and account features.
version: 0.0.1
homepage: https://github.com/lohanidamodar/flappwrite_account_kit

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  appwrite: ^3.0.0
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter: null
